export const POPULAR_COUNTRIES = [
    { code: 'JP', name: '일본', currency: 'JPY', symbol: '¥', emoji: '🇯🇵' },
    { code: 'VN', name: '베트남', currency: 'VND', symbol: '₫', emoji: '🇻🇳' },
    { code: 'TH', name: '태국', currency: 'THB', symbol: '฿', emoji: '🇹🇭' },
    { code: 'US', name: '미국/괌', currency: 'USD', symbol: '$', emoji: '🇺🇸' },
    { code: 'EU', name: '유럽', currency: 'EUR', symbol: '€', emoji: '🇪🇺' },
    { code: 'TW', name: '대만', currency: 'TWD', symbol: 'NT$', emoji: '🇹🇼' },
    { code: 'PH', name: '필리핀', currency: 'PHP', symbol: '₱', emoji: '🇵🇭' },
    { code: 'CN', name: '중국', currency: 'CNY', symbol: '¥', emoji: '🇨🇳' },
    {
        code: 'SG',
        name: '싱가포르',
        currency: 'SGD',
        symbol: 'S$',
        emoji: '🇸🇬',
    },
    {
        code: 'MY',
        name: '말레이시아',
        currency: 'MYR',
        symbol: 'RM',
        emoji: '🇲🇾',
    },
    {
        code: 'ID',
        name: '인도네시아',
        currency: 'IDR',
        symbol: 'Rp',
        emoji: '🇮🇩',
    },
    { code: 'HK', name: '홍콩', currency: 'HKD', symbol: 'HK$', emoji: '🇭🇰' },
    { code: 'AU', name: '호주', currency: 'AUD', symbol: 'A$', emoji: '🇦🇺' },
    { code: 'GB', name: '영국', currency: 'GBP', symbol: '£', emoji: '🇬🇧' },
    {
        code: 'NZ',
        name: '뉴질랜드',
        currency: 'NZD',
        symbol: 'NZ$',
        emoji: '🇳🇿',
    },
    { code: 'CA', name: '캐나다', currency: 'CAD', symbol: 'C$', emoji: '🇨🇦' },
    {
        code: 'MX',
        name: '멕시코',
        currency: 'MXN',
        symbol: 'Mex$',
        emoji: '🇲🇽',
    },
    { code: 'IN', name: '인도', currency: 'INR', symbol: '₹', emoji: '🇮🇳' },
    { code: 'RU', name: '러시아', currency: 'RUB', symbol: '₽', emoji: '🇷🇺' },
    { code: 'AE', name: 'UAE', currency: 'AED', symbol: 'د.إ', emoji: '🇦🇪' },
];
